version: "2.4"

services:
  # CaddyServer HTTP Container
  ## Controls the forward-facing web configuration of the machine.
  ## This includes the HTTP and HTTPS ports, SSL certificates, and more.
  ## This service includes the reverse-proxy mechanism for accessing services.
  http:
    container_name: http
    image: http_server:r0
    restart: always
    depends_on:
      - php-fpm
      - redis
    build:
      context: .
      dockerfile: ./http.Dockerfile
    ports:
      - "144.76.69.43:80:80" # HTTP
      - "144.76.69.43:443:443" # HTTP(s)
      - "144.76.69.43:8080:8080" # node1.amethyst.live
    volumes:
      - ./sys/data:/data
      - ./conf.d:/conf.d
        # Content for Servers
      - ./sys/content:/var/www/html
    networks:
      - http-network
    extra_hosts:
      # Allows access to the host machine hosted services.
      - "host.docker.internal:host-gateway"

  # PHP FPM Container
  ## Controls the PHP applications hosted on the machine.
  ## This includes the Laravel Framework, along with other PHP server applications.
  php-fpm:
    container_name: php-fpm
    image: php_fpm_8:r0
    restart: always
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./php-fpm.Dockerfile
    volumes:
      # Content for PHP Servers
      - ./sys/content:/var/www/html
    networks:
      - http-network

  # Redis Server
  ## Fast-access memory cache for the machine applications.
  redis:
    container_name: redis
    image: redis:6
    command: "redis-server --save 60 1 --loglevel warning"
    restart: always
    volumes:
      - ./sys/redis:/data
    networks:
      - http-network

  # Mailserver
  ## Production-ready fullstack but simple mail server (SMTP, IMAP, LDAP, Antispam, Antivirus, etc.) running inside a container.
  mailserver:
    container_name: mailserver
    image: mailserver/docker-mailserver:latest
    restart: always
    ports:
      - "144.76.69.43:25:25"
      - "144.76.69.43:465:465"
      - "144.76.69.43:587:587"
      - "144.76.69.43:993:993"
      - "144.76.69.43:143:143"
    volumes:
      - ./sys/docker-data/dms/mail-data/:/var/mail/
      - ./sys/docker-data/dms/mail-state/:/var/mail-state/
      - ./sys/docker-data/dms/mail-logs/:/var/log/mail/
      - ./sys/docker-data/dms/config/:/tmp/docker-mailserver/
      - ./sys/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mailerd.amethyst.live/mailerd.amethyst.live.crt:/etc/letsencrypt/live/mail.example.com/fullchain.pem:ro
      - ./sys/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mailerd.amethyst.live/mailerd.amethyst.live.key:/etc/letsencrypt/live/mail.example.com/privkey.pem:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - http-network
    hostname: mailerd
    domainname: amethyst.live
    env_file: ./mailserver.env
    stop_grace_period: 60s
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE

# Shared network mapping for inter-container communication.
networks:
  http-network:
    driver: bridge
