
services:
  # PC: Dockerized SuiteCRM Server
  suitecrm:
    image: 'bitnami/suitecrm:8'
    deploy:
      mode: 'global'
      resources:
        limits:
          cpus: '2.0'
          memory: '2G'
    restart: 'unless-stopped'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
    env_file: './.env'
    volumes:
      - './_/suitecrm/:/bitnami/suitecrm/'
    dns:
      - '1.1.1.1'
      - '1.0.0.1'
      - '8.8.8.8'
      - '8.4.4.8'